### ISSUE TITLE
invalid pretrained model

### ISSUE THREAD

**Issue by heluoshengmu** [ji-nu/yolo_pedestrian_detector#1]
hello, the file of download pretrained model:
https://drive.google.com/file/d/12fQhOYvfA833tD_xZ9c8cvcquV87EXiA/view?usp=sharing, is invalid.

**Comment by realrains** [comment]
Sorry @heluoshengmu 
I lost file and no longer maintain this repository.
Referenced repository link is below and you can download pre-trained model (may you need little bit graph modification)

* https://github.com/nilboy/tensorflow-yolo

**Comment by heluoshengmu** [comment]
thanks a bundle. have a nice day.
